
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: my_third_dbt_incremental_model
    description: "A starter dbt model"
    columns:
      - name: eventDay
        description: "The primary key for this table"
      - name: dailyUsers
        description: "active users in day"
      - name: entryTimestamp
        description: "time of entry"
